<script type="text/javascript">
    function getSystemBaseUrl(){
        	return BASE_URL='<?php 
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
                $storeManager->getStore()->getBaseUrl();
                echo $block->escapeJs($block->escapeUrl($storeManager->getStore()->getBaseUrl()));
                ?>';
    }  	
    var mage_country_code ='<?php echo $block->escapeJs($objectManager->get('Aramex\Shipping\Helper\Data')->getConfig('general/store_information/country_id')); ?>';
    var billing_aramex_cities = '';
    var shipping_aramex_cities = billing_aramex_cities;
    var active ='<?php echo $block->escapeJs($objectManager->get('Aramex\Shipping\Helper\Data')->getConfig('aramex/apilocationvalidator/active')); ?>';
</script>